#/control/alias RESOLUTION 1024
/control/alias RESOLUTION 50

/control/alias EPIDPOS -600 #mm

/gate/actor/addActor scatterVolumeInformationActor svia
/gate/actor/svia/attachTo      patient

#TODO front casing?

/gate/world/daughters/name beforecopper #entry before entering the phosporscreen, composed of various layers
/gate/world/daughters/insert box
/gate/beforecopper/setMaterial Air
/gate/beforecopper/geometry/setXLength 410 mm
/gate/beforecopper/geometry/setYLength 410 mm
/gate/beforecopper/geometry/setZLength 0.1 mm
/control/add POS_beforecopper 0.05 {EPIDPOS} # 0.1 tot 0
/gate/beforecopper/placement/setTranslation 0 0 {POS_beforecopper} mm 

/gate/world/daughters/name copperplate
/gate/world/daughters/insert box
/gate/copperplate/setMaterial Copper
/gate/copperplate/geometry/setXLength 410 mm
/gate/copperplate/geometry/setYLength 410 mm
/gate/copperplate/geometry/setZLength 1 mm
/control/add POS_copperplate -0.5 {EPIDPOS} # 0 tot -1
/gate/copperplate/placement/setTranslation 0 0 {POS_copperplate} mm 

/gate/world/daughters/name aftercopper #entry before entering the phosporscreen, composed of various layers
/gate/world/daughters/insert box
/gate/aftercopper/setMaterial Air
/gate/aftercopper/geometry/setXLength 410 mm
/gate/aftercopper/geometry/setYLength 410 mm
/gate/aftercopper/geometry/setZLength 0.1 mm
/control/add POS_aftercopper -1.05 {EPIDPOS} # -1 tot -1.1
/gate/aftercopper/placement/setTranslation 0 0 {POS_aftercopper} mm 

/gate/world/daughters/name overcoat
/gate/world/daughters/insert box
/gate/overcoat/setMaterial G4_CELLULOSE_CELLOPHANE # TODO should be cellulose acetate
/gate/overcoat/geometry/setXLength 410 mm
/gate/overcoat/geometry/setYLength 410 mm
/gate/overcoat/geometry/setZLength 0.1 mm # TODO no idea
/control/add POS_overcoat -1.15 {EPIDPOS} # -1.1 tot -1.2
/gate/overcoat/placement/setTranslation 0 0 {POS_overcoat} mm 

/gate/world/daughters/name support
/gate/world/daughters/insert box
/gate/support/setMaterial Air #no idea
/gate/support/geometry/setXLength 410 mm
/gate/support/geometry/setYLength 410 mm
/gate/support/geometry/setZLength 0.1 mm # TODO no idea
/control/add POS_support -1.25 {EPIDPOS} # -1.2 tot -1.3
/gate/support/placement/setTranslation 0 0 {POS_support} mm 

/gate/world/daughters/name phosphorscreen
/gate/world/daughters/insert box
/gate/phosphorscreen/setMaterial G4_GADOLINIUM_OXYSULFIDE # TODO must set density to 5.64g/cm3, because is 7.44 in Geant4
/gate/phosphorscreen/geometry/setXLength 410 mm
/gate/phosphorscreen/geometry/setYLength 410 mm
/gate/phosphorscreen/geometry/setZLength 0.1788 mm # TODO when G4_GADOLINIUM_OXYSULFIDE density is set to 5.64, thickness must be set to 0.2358mm
/control/add POS_phosphorscreen -1.5 {EPIDPOS} # -1.3212 tot -1.6788
/gate/phosphorscreen/placement/setTranslation 0 0 {POS_phosphorscreen} mm 

## EPID PhaseSpace

/gate/actor/addActor PhaseSpaceActor FlightRecorder3
/gate/actor/FlightRecorder3/save                     output/phosphorscreen.root
/gate/actor/FlightRecorder3/attachTo                 phosphorscreen
/gate/actor/FlightRecorder3/useVolumeFrame           true
/gate/actor/FlightRecorder3/storeOutgoingParticles   false
/gate/actor/FlightRecorder3/enableTransmission       true
/gate/actor/FlightRecorder3/enablePrimary            true

## EPID PhaseSpace FILTERTESTS

#/gate/actor/addActor PhaseSpaceActor FlightRecorder8
#/gate/actor/FlightRecorder8/save                     output/phosphorscreen-trans.root
#/gate/actor/FlightRecorder8/attachTo                 phosphorscreen
#/gate/actor/FlightRecorder8/useVolumeFrame           true
#/gate/actor/FlightRecorder8/storeOutgoingParticles   false
#/gate/actor/FlightRecorder8/enableTransmission       false
#/gate/actor/FlightRecorder8/enablePrimary            false
#/gate/actor/FlightRecorder8/addFilter                         transmissionFilter
#/gate/actor/FlightRecorder8/transmissionFilter/setTransmission true

#/gate/actor/addActor PhaseSpaceActor FlightRecorder9
#/gate/actor/FlightRecorder9/save                     output/phosphorscreen-nontrans.root
#/gate/actor/FlightRecorder9/attachTo                 phosphorscreen
#/gate/actor/FlightRecorder9/useVolumeFrame           true
#/gate/actor/FlightRecorder9/storeOutgoingParticles   false
#/gate/actor/FlightRecorder9/enableTransmission       false
#/gate/actor/FlightRecorder9/enablePrimary            false
#/gate/actor/FlightRecorder8/addFilter                         transmissionFilter
#/gate/actor/FlightRecorder8/transmissionFilter/setTransmission false

## EPID (TLE) DOSE, all DOSE

/gate/actor/addActor DoseActor      epiddoseall
/gate/actor/epiddoseall/save              output/epiddose-all.mhd
/gate/actor/epiddoseall/attachTo          phosphorscreen
#/gate/actor/epiddoseall/stepHitType       middle
/gate/actor/epiddoseall/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddoseall/enableDose            true
/gate/actor/epiddoseall/enableUncertaintyDose true
/gate/actor/epiddoseall/enableEdep            true
/gate/actor/epiddoseall/enableUncertaintyEdep true
/gate/actor/epiddoseall/enableNumberOfHits true

## EPID (TLE) DOSE, PHOTON TRANSMISSION DOSE

/gate/actor/addActor DoseActor      epiddosetrans
/gate/actor/epiddosetrans/save              output/epiddose-trans.mhd
/gate/actor/epiddosetrans/attachTo          phosphorscreen
#/gate/actor/epiddosetrans/stepHitType       middle
/gate/actor/epiddosetrans/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosetrans/enableDose            true
/gate/actor/epiddosetrans/enableUncertaintyDose true
/gate/actor/epiddosetrans/enableEdep            true
/gate/actor/epiddosetrans/enableUncertaintyEdep true
/gate/actor/epiddosetrans/enableNumberOfHits true
/gate/actor/epiddosetrans/setTransmission true

/gate/actor/addActor DoseActor      epiddosetransfilter
/gate/actor/epiddosetransfilter/save              output/epiddose-nontransfilter.mhd
/gate/actor/epiddosetransfilter/attachTo          phosphorscreen
#/gate/actor/epiddosetransfilter/stepHitType       middle
/gate/actor/epiddosetransfilter/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosetransfilter/enableDose            true
/gate/actor/epiddosetransfilter/enableUncertaintyDose true
/gate/actor/epiddosetransfilter/enableEdep            true
/gate/actor/epiddosetransfilter/enableUncertaintyEdep true
/gate/actor/epiddosetransfilter/enableNumberOfHits true
/gate/actor/epiddosetransfilter/addFilter                         transmissionFilter
/gate/actor/epiddosetransfilter/transmissionFilter/setTransmission false

## EPID (TLE) DOSE, PHOTON NON TRANSMISSION (SCATTER+PHOTON SECONDARY) DOSE

/gate/actor/addActor DoseActor      epiddosescatter
/gate/actor/epiddosescatter/save              output/epiddose-nontrans.mhd
/gate/actor/epiddosescatter/attachTo          phosphorscreen
#/gate/actor/epiddosescatter/stepHitType       middle
/gate/actor/epiddosescatter/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosescatter/enableDose            true
/gate/actor/epiddosescatter/enableUncertaintyDose true
/gate/actor/epiddosescatter/enableEdep            true
/gate/actor/epiddosescatter/enableUncertaintyEdep true
/gate/actor/epiddosescatter/enableNumberOfHits true
/gate/actor/epiddosescatter/setTransmission false

## EPID (TLE) DOSE, electron positron DOSE

/gate/actor/addActor DoseActor      epiddosesecon
/gate/actor/epiddosesecon/save              output/epiddose-nonphot.mhd
/gate/actor/epiddosesecon/attachTo          phosphorscreen
#/gate/actor/epiddosesecon/stepHitType       middle
/gate/actor/epiddosesecon/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosesecon/enableDose            true
/gate/actor/epiddosesecon/enableUncertaintyDose true
/gate/actor/epiddosesecon/enableEdep            true
/gate/actor/epiddosesecon/enableUncertaintyEdep true
/gate/actor/epiddosesecon/enableNumberOfHits true
/gate/actor/epiddosesecon/addFilter                         particleFilter
/gate/actor/epiddosesecon/particleFilter/addParticle        e-
/gate/actor/epiddosesecon/particleFilter/addParticle        e+



# TODO not required: rear overcoat, photodiode, rear casing



