############# kill after support
/gate/actor/addActor KillActor       ahnuld
/gate/actor/ahnuld/save             ahnuld.txt
/gate/actor/ahnuld/attachTo         support
/gate/actor/ahnuld/addFilter                         transmissionFilter
/gate/actor/ahnuld/transmissionFilter/setTransmission true
############# END OF TEST

## EPID PhaseSpace

/gate/actor/addActor PhaseSpaceActor FlightRecorder3
/gate/actor/FlightRecorder3/save                     output/phosphorscreen.root
/gate/actor/FlightRecorder3/attachTo                 phosphorscreen
/gate/actor/FlightRecorder3/useVolumeFrame           true
/gate/actor/FlightRecorder3/storeOutgoingParticles   false
/gate/actor/FlightRecorder3/enableTransmission       true
/gate/actor/FlightRecorder3/enablePrimary            true

## EPID (TLE) DOSE, all DOSE

/gate/actor/addActor DoseActor      epiddoseall
/gate/actor/epiddoseall/save              output/epiddose-all.mhd
/gate/actor/epiddoseall/attachTo          phosphorscreen
#/gate/actor/epiddoseall/stepHitType       middle
/gate/actor/epiddoseall/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddoseall/enableDose            true
/gate/actor/epiddoseall/enableUncertaintyDose true
/gate/actor/epiddoseall/enableEdep            true
/gate/actor/epiddoseall/enableUncertaintyEdep true
/gate/actor/epiddoseall/enableNumberOfHits true
