############# kill after support
#/gate/actor/addActor KillActor       ahnuld
#/gate/actor/ahnuld/save             ahnuld.txt
#/gate/actor/ahnuld/attachTo         killvolume
#/gate/actor/ahnuld/addFilter                         transmissionFilter
#/gate/actor/ahnuld/transmissionFilter/setTransmission false
############# END OF TEST

## EPID PhaseSpace

/gate/actor/addActor PhaseSpaceActor FlightRecorder3
/gate/actor/FlightRecorder3/save                     output/phosphorscreen.root
/gate/actor/FlightRecorder3/attachTo                 phosphorscreen
/gate/actor/FlightRecorder3/useVolumeFrame           true
/gate/actor/FlightRecorder3/storeOutgoingParticles   false
/gate/actor/FlightRecorder3/enableTransmission       true
/gate/actor/FlightRecorder3/enablePrimary            true

## EPID (TLE) DOSE, all DOSE

/gate/actor/addActor DoseActor      epiddose
/gate/actor/epiddose/save              output/epiddose.mhd
/gate/actor/epiddose/attachTo          phosphorscreen
#/gate/actor/epiddose/stepHitType       middle
/gate/actor/epiddose/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddose/enableDose            true
/gate/actor/epiddose/enableUncertaintyDose true
/gate/actor/epiddose/enableEdep            true
/gate/actor/epiddose/enableUncertaintyEdep true
/gate/actor/epiddose/enableNumberOfHits true

/gate/actor/addActor TLEDoseActor      epiddosetle
/gate/actor/epiddosetle/save              output/epiddose-tle.mhd
/gate/actor/epiddosetle/attachTo          phosphorscreen
#/gate/actor/epiddosetle/stepHitType       middle
/gate/actor/epiddosetle/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosetle/enableDose            true
/gate/actor/epiddosetle/enableUncertaintyDose true
/gate/actor/epiddosetle/enableEdep            true
/gate/actor/epiddosetle/enableUncertaintyEdep true
#/gate/actor/epiddosetle/enableNumberOfHits true
