/control/alias RESOLUTION 1024
#/control/alias RESOLUTION 50

/gate/actor/addActor scatterVolumeInformationActor svia
/gate/actor/svia/attachTo      patient

#TODO front casing?

/gate/world/daughters/name beforecopper #entry before entering the phosporscreen, composed of various layers
/gate/world/daughters/insert box
/gate/beforecopper/setMaterial Air
/gate/beforecopper/geometry/setXLength 410 mm
/gate/beforecopper/geometry/setYLength 410 mm
/gate/beforecopper/geometry/setZLength 0.1 mm
/gate/beforecopper/placement/setTranslation 0 0 -148.45 mm #layer is <148.4-148.5>

/gate/actor/addActor PhaseSpaceActor FlightRecorder
/gate/actor/FlightRecorder/save                     output/beforecopper.root
/gate/actor/FlightRecorder/attachTo                 beforecopper
/gate/actor/FlightRecorder/useVolumeFrame           true
/gate/actor/FlightRecorder/storeOutgoingParticles   false
/gate/actor/FlightRecorder/enableTransmission       true
#/gate/actor/FlightRecorder/enablePrimary            true

/gate/world/daughters/name copperplate
/gate/world/daughters/insert box
/gate/copperplate/setMaterial Copper
/gate/copperplate/geometry/setXLength 410 mm
/gate/copperplate/geometry/setYLength 410 mm
/gate/copperplate/geometry/setZLength 1 mm
/gate/copperplate/placement/setTranslation 0 0 -149 mm #layer is <148.5-149.5>

/gate/world/daughters/name aftercopper #entry before entering the phosporscreen, composed of various layers
/gate/world/daughters/insert box
/gate/aftercopper/setMaterial Air
/gate/aftercopper/geometry/setXLength 410 mm
/gate/aftercopper/geometry/setYLength 410 mm
/gate/aftercopper/geometry/setZLength 0.1 mm
/gate/aftercopper/placement/setTranslation 0 0 -149.55 mm #layer is <149.5-149.6>

/gate/actor/addActor PhaseSpaceActor FlightRecorder2
/gate/actor/FlightRecorder2/save                     output/aftercopper.root
/gate/actor/FlightRecorder2/attachTo                 aftercopper
/gate/actor/FlightRecorder2/useVolumeFrame           true
/gate/actor/FlightRecorder2/storeOutgoingParticles   false
/gate/actor/FlightRecorder2/enableTransmission       true
/gate/actor/FlightRecorder2/enablePrimary            true

############# TEST
/gate/actor/addActor PhaseSpaceActor FlightRecorder4
/gate/actor/FlightRecorder4/save                     output/aftercopper-P.root
/gate/actor/FlightRecorder4/attachTo                 aftercopper
/gate/actor/FlightRecorder4/useVolumeFrame           true
/gate/actor/FlightRecorder4/storeOutgoingParticles   false
/gate/actor/FlightRecorder4/enableTransmission       true
/gate/actor/FlightRecorder4/enablePrimary            true
/gate/actor/FlightRecorder4/addFilter                         scatterVolumeFilter
/gate/actor/FlightRecorder4/scatterVolumeFilter/setScatterVolume          patient_voxel_phys_Z

#/gate/actor/addActor FluenceActor      epidfluence
#/gate/actor/epidfluence/save              output/epidfluence.mhd
#/gate/actor/epidfluence/attachTo          aftercopper
#/gate/actor/epidfluence/stepHitType       pre
#/gate/actor/epidfluence/setResolution     {RESOLUTION} {RESOLUTION} 1
#/gate/actor/epidfluence/enableScatter     true

############# END OF TEST

/gate/world/daughters/name overcoat
/gate/world/daughters/insert box
/gate/overcoat/setMaterial G4_CELLULOSE_CELLOPHANE # TODO should be cellulose acetate
/gate/overcoat/geometry/setXLength 410 mm
/gate/overcoat/geometry/setYLength 410 mm
/gate/overcoat/geometry/setZLength 0.1 mm # TODO no idea
/gate/overcoat/placement/setTranslation 0 0 -149.65 mm #layer is <149.6-149.7>

/gate/world/daughters/name support
/gate/world/daughters/insert box
/gate/support/setMaterial Air #no idea
/gate/support/geometry/setXLength 410 mm
/gate/support/geometry/setYLength 410 mm
/gate/support/geometry/setZLength 0.1 mm # TODO no idea
/gate/support/placement/setTranslation 0 0 -149.65 mm #layer is <149.6-149.7>

/gate/world/daughters/name phosphorscreen
/gate/world/daughters/insert box
/gate/phosphorscreen/setMaterial G4_GADOLINIUM_OXYSULFIDE # TODO must set density to 5.64g/cm3, because is 7.44 in Geant4
/gate/phosphorscreen/geometry/setXLength 410 mm
/gate/phosphorscreen/geometry/setYLength 410 mm
/gate/phosphorscreen/geometry/setZLength 0.1788 mm # TODO when G4_GADOLINIUM_OXYSULFIDE density is set to 5.64, thickness must be set to 0.2358mm
/gate/phosphorscreen/placement/setTranslation 0 0 -149.825 mm #layer does not excede <149.75-150.00>

## EPID PhaseSpace

/gate/actor/addActor PhaseSpaceActor FlightRecorder3
/gate/actor/FlightRecorder3/save                     output/phosphorscreen.root
/gate/actor/FlightRecorder3/attachTo                 phosphorscreen
/gate/actor/FlightRecorder3/useVolumeFrame           true
/gate/actor/FlightRecorder3/storeOutgoingParticles   false
/gate/actor/FlightRecorder3/enableTransmission       true
/gate/actor/FlightRecorder3/enablePrimary            true

## EPID (TLE) DOSE, PHOTON TRANSMISSION DOSE

/gate/actor/addActor DoseActor      epiddosetrans
/gate/actor/epiddosetrans/save              output/epiddose-trans.mhd
/gate/actor/epiddosetrans/attachTo          phosphorscreen
/gate/actor/epiddosetrans/stepHitType       pre
/gate/actor/epiddosetrans/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosetrans/enableDose            true
/gate/actor/epiddosetrans/enableUncertaintyDose true
/gate/actor/epiddosetrans/enableEdep            true
/gate/actor/epiddosetrans/enableUncertaintyEdep true
/gate/actor/epiddosetrans/enableNumberOfHits true
#/gate/actor/epiddosetrans/addFilter                         particleFilter
#/gate/actor/epiddosetrans/particleFilter/addParticle        gamma
/gate/actor/epiddosetrans/addFilter                         transmissionFilter
/gate/actor/epiddosetrans/transmissionFilter/setTransmission true

## EPID (TLE) DOSE, PHOTON NON TRANSMISSION (SCATTER+PHOTON SECONDARY) DOSE

/gate/actor/addActor DoseActor      epiddosescatter
/gate/actor/epiddosescatter/save              output/epiddose-nontrans.mhd
/gate/actor/epiddosescatter/attachTo          phosphorscreen
/gate/actor/epiddosescatter/stepHitType       pre
/gate/actor/epiddosescatter/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosescatter/enableDose            true
/gate/actor/epiddosescatter/enableUncertaintyDose true
/gate/actor/epiddosescatter/enableEdep            true
/gate/actor/epiddosescatter/enableUncertaintyEdep true
/gate/actor/epiddosescatter/enableNumberOfHits true
/gate/actor/epiddosescatter/addFilter                         particleFilter
/gate/actor/epiddosescatter/particleFilter/addParticle        gamma
/gate/actor/epiddosescatter/addFilter                         transmissionFilter
/gate/actor/epiddosescatter/transmissionFilter/setTransmission false
#/gate/actor/epiddosescatter/addFilter                         scatterVolumeFilter
#/gate/actor/epiddosescatter/scatterVolumeFilter/setScatterVolume          patient

## EPID (TLE) DOSE, electron positron DOSE

/gate/actor/addActor DoseActor      epiddosesecon
/gate/actor/epiddosesecon/save              output/epiddose-nonphot.mhd
/gate/actor/epiddosesecon/attachTo          phosphorscreen
/gate/actor/epiddosesecon/stepHitType       pre
/gate/actor/epiddosesecon/setResolution     {RESOLUTION} {RESOLUTION} 1
/gate/actor/epiddosesecon/enableDose            true
/gate/actor/epiddosesecon/enableUncertaintyDose true
/gate/actor/epiddosesecon/enableEdep            true
/gate/actor/epiddosesecon/enableUncertaintyEdep true
/gate/actor/epiddosesecon/enableNumberOfHits true
/gate/actor/epiddosesecon/addFilter                         particleFilter
/gate/actor/epiddosesecon/particleFilter/addParticle        e-
/gate/actor/epiddosesecon/particleFilter/addParticle        e+



# TODO not required: rear overcoat, photodiode, rear casing



