/gate/physics/addPhysicsList emlivermore
#/gate/physics/addPhysicsList QGSP_BIC_HP_EMY

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      patient 0.1 mm
/gate/physics/Electron/SetCutInRegion   patient 0.1 mm
/gate/physics/Positron/SetCutInRegion   patient 0.1 mm

/gate/physics/Gamma/SetCutInRegion      mylinac 10 mm
/gate/physics/Electron/SetCutInRegion   mylinac 10 mm
/gate/physics/Positron/SetCutInRegion   mylinac 10 mm

/gate/physics/Gamma/SetCutInRegion      phosphorscreen 0.1 mm
/gate/physics/Electron/SetCutInRegion   phosphorscreen 0.1 mm
/gate/physics/Positron/SetCutInRegion   phosphorscreen 0.1 mm

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

# StepLimiter *required*
#/gate/physics/SetMaxStepSizeInRegion patient 1 mm
#/gate/physics/ActivateStepLimiter proton
#/gate/physics/ActivateStepLimiter deuteron
#/gate/physics/ActivateStepLimiter triton
#/gate/physics/ActivateStepLimiter alpha
#/gate/physics/ActivateStepLimiter GenericIon

#/gate/physics/SetMinKineticEnergyInRegion patient 100 MeV
#/gate/physics/ActivateSpecialCuts proton

